src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(name="category")
 * use repository for handy tree functions
 * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\NestedTreeRepository")
 */
//* @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")

class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(length=64)
     */
    private $name;

    /**
     * @ORM\Column(length=64, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(length=256, nullable=true)
     */
    private $meta_description;

    /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="lft", type="integer")
     */
    private $lft;

    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @Gedmo\TreeRight
     * @ORM\Column(name="rgt", type="integer")
     */
    private $rgt;

    /**
     * @Gedmo\TreeRoot
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="tree_root", referencedColumnName="id", onDelete="CASCADE")
     */
    private $root;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

    /**
     * One Product has Many Features.
     * @ORM\OneToMany(targetEntity="Product", mappedBy="category", indexBy="id")
     */
    private $products;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullName;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->children = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Category
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return Category
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLft()
    {
        return $this->lft;
    }

    /**
     * @param mixed $lft
     * @return Category
     */
    public function setLft($lft)
    {
        $this->lft = $lft;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLvl()
    {
        return $this->lvl;
    }

    /**
     * @param mixed $lvl
     * @return Category
     */
    public function setLvl($lvl)
    {
        $this->lvl = $lvl;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRgt()
    {
        return $this->rgt;
    }

    /**
     * @param mixed $rgt
     * @return Category
     */
    public function setRgt($rgt)
    {
        $this->rgt = $rgt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * @param mixed $root
     * @return Category
     */
    public function setRoot($root)
    {
        $this->root = $root;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param mixed $parent
     * @return Category
     */
    public function setParent($parent)
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * @param mixed $children
     * @return Category
     */
    public function setChildren($children)
    {
        $this->children = $children;
        return $this;
    }

    /**
     * @return mixed
     */
    public function isActive()
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     * @return Category
     */
    public function setIsActive(bool $isActive): Category
    {
        $this->isActive = $isActive;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getMetaDescription()
    {
        return $this->meta_description;
    }

    /**
     * @param mixed $meta_description
     * @return Category
     */
    public function setMetaDescription($meta_description)
    {
        $this->meta_description = $meta_description;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getProducts()
    {
        return $this->products;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function forTree()
    {
        return sprintf('%s %s', str_repeat('--', $this->getLvl()), $this->getName());
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

}

templates/themes/digi/catalog/products.html.twig
{% extends 'themes/digi/layout.html.twig' %}

{% block title %}
    {{ category.name }} / Mikotek.RU
{% endblock %}

{% block meta_description %}{{ category.metaDescription }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <i class="fa fa-dashboard"></i> <a href="{{ path('homepage') }}"> Главная</a>
        </li>
        <li class="breadcrumb-item active">
            <i class="fa fa-table"></i> {{ category.name }}
        </li>
    </ol>
{% endblock %}

{% block body %}

    {% include 'themes/digi/common/flashes.html.twig' %}

    {#{% if current_filters|length %}#}
        {#<div class="alert alert-secondary" role="alert">#}
            {#<i class="fa fa-filter"></i> Filters:#}
            {#{% for field, filter in current_filters %}#}
                {#<span class="badge badge-secondary">{{ field }}: {{ filter }}</span>#}
            {#{% endfor %}#}
            {#|#}
            {#<a href="{{ path('backend_reset_filter', {'model': model}) }}"><i class="fa fa-times"></i> reset all</a>#}
        {#</div>#}
    {#{% endif %}#}

    <div class="card mb-2 box-shadow">
        <div class="card-body">
        Sort by:
            {{ knp_pagination_sortable(pagination, 'Name', 'product.name') }}
            ||
            {{ knp_pagination_sortable(pagination, 'Price', 'product.price') }}
        </div>
    </div>
    <div class="row text-center">
        {% for index, row in pagination %}
            <div class="col-sm-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal"><a
                            class="alert-link"
                            href="{{ path('product_show', {'slug': category.slug, 'id': row.id}) }}">{{ row.name }}</a></h4>
                    </div>
                    <div class="card-body">
                        {% if row.pic %}
                            <a data-fancybox="gallery" target="_blank" href="{{ asset('/uploads/pics/' ~ row.pic) }}"><img
                                        src="{{ asset('/uploads/pics/' ~ row.pic) | imagine_filter('thumb_square_160') }}" /></a>
                        {% else %}
                            ---
                        {% endif %}

                        <h1 class="card-title pricing-card-title product_price">{{ row.price }} ₽</h1>

                        <div class="m-sm-auto">Оптом: {{ row.priceOpt }}₽</div>

                        <div class="text-center">
                            <span class="badge badge-{{ row.statusAsCssClass }}">{{ row.statusRus }}</span>
                        </div>

                        <div class="text-left">
                            {{ row.announce | nl2br | raw }}
                        </div>

                        {% if row.isAvailableToOrder %}
                            <a href="{{ path('add_to_cart', {'id': row.id}) }}"
                               class="btn btn-lg btn-block btn-primary text-white"><i
                                        class="fa fa-cart-plus"></i> В корзину</a>
                        {% else %}
                            <a href="javascript:;"
                               class="btn btn-lg btn-block btn-secondary text-white"><i
                                        class="fa fa-info-circle"></i> {{ row.statusRus }}</a>
                        {% endif %}

                        <a href="{{ path('product_show', {'slug': category.slug, 'id': row.id}) }}"
                           class="btn btn-lg btn-block btn-success text-white"><i
                                    class="fa fa-search"></i> Просмотр</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    {# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
        <div class="count">
            Total rows: {{ pagination.getTotalItemCount }}
        </div>
    </div>

{% endblock %}


{% block filter_form %}
    {% include 'admin/common/filter_form.html.twig' with {'filter_form': filter_form} %}
{% endblock %}

templates/themes/digi/catalog/products_vitrine.html.twig
{% include 'themes/digi/common/flashes.html.twig' %}

<div class="row text-center">
    {% for index, row in rows %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ row.name }}</h4>
                </div>
                <div class="card-body">
                    {% if row.pic %}
                        <a data-fancybox="gallery" target="_blank" href="{{ asset('/uploads/pics/' ~ row.pic) }}"><img
                                    src="{{ asset('/uploads/pics/' ~ row.pic) | imagine_filter('thumb_square_160') }}" /></a>
                    {% else %}
                        ---
                    {% endif %}

                    <h1 class="card-title pricing-card-title product_price">{{ row.price }} ₽</h1>
                    <div class="m-sm-auto">Оптом: {{ row.priceOpt }}₽</div>

                    {{ row.description }}

                    <a href="{{ path('add_to_cart', {'id': row.id}) }}"
                       class="btn btn-lg btn-block btn-primary text-white"><i
                                class="fa fa-cart-plus"></i> Add to cart</a>

                    {#<button type="button" class="btn btn-lg btn-block btn-primary"><i class="fa fa-cart-plus"></i> Buy</button>#}
                    <a href="{{ path('product_show', {'slug': row.category.slug, 'id': row.id}) }}"
                       class="btn btn-lg btn-block btn-success text-white"><i
                                class="fa fa-search"></i> View</a>

                    {#<ul class="list-unstyled mt-3 mb-4">#}
                        {#<li>10 users included</li>#}
                        {#<li>2 GB of storage</li>#}
                        {#<li>Email support</li>#}
                        {#<li>Help center access</li>#}
                    {#</ul>#}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>

{#<div class="btn-group alg-right-pad">#}
    {#<button type="button" class="btn btn-default"><strong>1235  </strong>items</button>#}
    {#<div class="btn-group">#}
        {#<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">#}
            {#Sort Products &nbsp;#}
            {#<span class="caret"></span>#}
        {#</button>#}
        {#<ul class="dropdown-menu">#}
            {#<li><a href="#">By Price Low</a></li>#}
            {#<li class="divider"></li>#}
            {#<li><a href="#">By Price High</a></li>#}
            {#<li class="divider"></li>#}
            {#<li><a href="#">By Popularity</a></li>#}
            {#<li class="divider"></li>#}
            {#<li><a href="#">By Reviews</a></li>#}
        {#</ul>#}
    {#</div>#}
{#</div>#}